# -*- coding: utf-8 -*-
"""14681

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ArhJyKO2fFlMBk1qWFDQyP33tz5XYDq2
"""

x = int(input())
y = int(input())

if x > 0 and y > 0:
    print('1')

elif x <0 and y >0:
    print('2')

elif x < 0 and y < 0:
    print('3')

elif x > 0 and y< 0:
    print('4')