# -*- coding: utf-8 -*-
"""2525

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ArhJyKO2fFlMBk1qWFDQyP33tz5XYDq2
"""

H,M = map(int,input().split())
N = int(input()) #굽는 시간

H += N //60 #60을 나누는 몫
M += N % 60 # 60으로 나눠지는 나머지 

if M >=60:
    H +=1
    M -=60

elif H>=24:
    H-=24

print(H,M)