# -*- coding: utf-8 -*-
"""2753

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ArhJyKO2fFlMBk1qWFDQyP33tz5XYDq2
"""

year = int(input())

if year % 4 == 0 and (year % 100 != 0 or year % 400 ==0):
    
    print('1')
else:
    print('0')