# -*- coding: utf-8 -*-
"""2884

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ArhJyKO2fFlMBk1qWFDQyP33tz5XYDq2
"""

H,M = map(int,input().split())

if H > 0 and M < 45:
    print(H-1, 60-45+M)

elif M>44:
    print(H, M-45)

else:
    print(23, M+15)