# -*- coding: utf-8 -*-
"""9498

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ArhJyKO2fFlMBk1qWFDQyP33tz5XYDq2
"""

score = int(input())

if score >= 90:
    print('A')
elif score >= 80:
    print('B')
elif score >= 70:
    print('C')
elif score >= 60:
    print('D')
else:
    print('F')