# -*- coding: utf-8 -*-
"""Chapter06_03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRTGkYdq-8Dud0WKPSPyTH2yXaHPjRKT
"""

n = int(input())

value = [ list(input().split()) for _ in range(n)] #값과 숫자를 리스트 형식으로 받기


value.sort(key = lambda x : x[1]) #람다식을 사용하여 내림차순 정렬 , key-value부분에서 value부분만 추출

for i in value: #value 데이터에서 값 추출
    print(i[0], end = ' ')

