# -*- coding: utf-8 -*-
"""100998

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkrsWCvHXWPxYCWiEAat7b-SyjZHYDW0
"""

#두 수를 입력 받아서 곱하라
A, B =  map(int, input().split())

print( A * B)

