# -*- coding: utf-8 -*-
"""10718

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oj2FozbjEQF6FqmpaQ_H7lxorSuZV8vT
"""

#강한친구 대한 육군 한 줄에 한 번씩 출력

print("강한친구 대한육군")
print("강한친구 대한육군")