# -*- coding: utf-8 -*-
"""10869

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkrsWCvHXWPxYCWiEAat7b-SyjZHYDW0
"""

A, B =  map(int, input().split())

print( A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)

