# -*- coding: utf-8 -*-
"""10926

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkrsWCvHXWPxYCWiEAat7b-SyjZHYDW0
"""

ID = input()
print(ID +'??!')