# -*- coding: utf-8 -*-
"""18108

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkrsWCvHXWPxYCWiEAat7b-SyjZHYDW0
"""

year1 = int(input())
print(year1 - 543)