# -*- coding: utf-8 -*-
"""2557

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yaGKiAecBEXwi2M4CtKciKLcQSb2kc3S
"""

#2557
#Hello world!를 출력하라

print("Hello World!")