# -*- coding: utf-8 -*-
"""2588

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkrsWCvHXWPxYCWiEAat7b-SyjZHYDW0
"""

A = int(input())
B = int(input())
print(A * (B % 10))
print(A * (B % 100 // 10))
print(A * (B // 100))
print(A * B)