# -*- coding: utf-8 -*-
"""Bac_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ne_j_BKhPSmZMPHdCaYB1dya8W9zfNQ
"""

print("Hello World!")

print("강한친구 대한육군")
print("강한친구 대한육군")

user = input()

a, b = input().split() # input 뒤에 split 써도 되는지 몰랐음
print(int(a)+int(b))

a, b = input().split()
print(int(a)-int(b))

a, b = input().split()
print(int(a)*int(b))

a, b = input().split()
print(int(a)/int(b))

# 백준 1 - 9

a, b = input().split() # 더 간단한 코드는 없을까? -> 틀렸다
print(int(a)+int(b))
print(int(a)-int(b))
print(int(a)*int(b))
print(int(a)/int(b))
print(int(a)%int(b))

# 백준 1 - 9 

# 틀렸다
user = [input().split()]
for a,b in user :
    print(int(a)+int(b))
    print(int(a)-int(b))
    print(int(a)*int(b))
    print(int(a)/int(b))
    print(int(a)%int(b))

## 블로그에서는 map 함수를 사용한것을 발견

a,b = map(int, input().split())
print(a+b, a-b, a*b, a/b, a%b, sep="\n")

# 틀렸다고 나옴 -> ??

a, b = input().split()
a = int(a)
b = int(b)
print(a+b)
print(a-b)
print(a*b)
print(int(a/b))
print(a%b)

# 백준 1 - 10

user = input()
print(f"{user}??!")

# 백준 1 - 11

2541 - 1998

user = input()
print(int(user) - 543)

# bac 1 - 12
A, B, C = map(int, input().split())
print((A+B)%C, 
      ((A%C) + (B%C))%C , 
      (A*B)%C, 
      ((A%C) * (B%C))%C,
      sep="\n")

# bac 1 - 13

## input 두번 해야하나?

user = input()
user2 = input()
for i in user2[::-1] :
    i = int(i)
    print(i * int(user))
print(int(user) * int(user2))


## 붙여쓴 숫자를 자리수 별로 쪼개야함

