# -*- coding: utf-8 -*-
"""chapter02_01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zagUakmkOzoLMDzXw196mqW3qVNZGfHo
"""

#거스름돈, 동전 최소 갯수

money = [500,100,50,10]

pay = 1260
count = []

for i in money:
    
    count.append(pay //i)
    pay %= i

print(count)
print(sum(count))

